### A base TSConfig for working with Node LTS + Strictest.

Add the package to your `"devDependencies"`:

```sh
npm install --save-dev @tsconfig/node-lts-strictest
yarn add --dev @tsconfig/node-lts-strictest
```

Add to your `tsconfig.json`:

```json
"extends": "@tsconfig/node-lts-strictest/tsconfig.json"
```

---

The `tsconfig.json`: 

```jsonc
// This file was autogenerated by a script
// Equivalent to a config of: strictest extends node18
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Node LTS + Strictest",
  "_version": "18.12.1",
  "compilerOptions": {
    "lib": [
      "es2022"
    ],
    "module": "commonjs",
    "target": "es2022",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "allowUnusedLabels": false,
    "allowUnreachableCode": false,
    "exactOptionalPropertyTypes": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noPropertyAccessFromIndexSignature": true,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "importsNotUsedAsValues": "error",
    "checkJs": true
  }
}
```

You can find the [code here](https://github.com/tsconfig/bases/blob/master/bases/node-lts-strictest.json).
